CREATE DATABASE IF NOT EXISTS apresto;
USE apresto;

CREATE TABLE utilisateur(
   idUTIL BIGINT AUTO_INCREMENT,
   emailUtil VARCHAR(100),
   loginUtil VARCHAR(100),
   mdpUtil VARCHAR(255),
   PRIMARY KEY(idUTIL)
);

CREATE TABLE commande(
   idCOM BIGINT AUTO_INCREMENT,
   etatCOM VARCHAR(30),
   date_horaireCOM DATETIME,
   valeurTTC DECIMAL(13,3),
   typeCOM TINYINT UNSIGNED,
   TVA TINYINT UNSIGNED,
   idUTIL BIGINT NOT NULL,
   PRIMARY KEY(idCOM),
   FOREIGN KEY(idUTIL) REFERENCES utilisateur(idUTIL)
);

CREATE TABLE produit(
   idPROD BIGINT AUTO_INCREMENT,
   libellePROD VARCHAR(100),
   prixHT DECIMAL(13,3),
   PRIMARY KEY(idPROD)
);

CREATE TABLE ligne_de_commande(
   idLIGNCOM BIGINT AUTO_INCREMENT,
   quantiteProduit INT,
   totalHT DECIMAL(13,3),
   idCOM BIGINT NOT NULL,
   idPROD BIGINT NOT NULL,
   PRIMARY KEY(idLIGNCOM),
   FOREIGN KEY(idCOM) REFERENCES commande(idCOM),
   FOREIGN KEY(idPROD) REFERENCES produit(idPROD)
);
